# Generated by Django 2.2 on 2019-04-18 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='show_movie', to='dashboard.movie'),
        ),
        migrations.AlterField(
            model_name='show',
            name='screen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='show_screen', to='dashboard.screen'),
        ),
        migrations.AlterField(
            model_name='show',
            name='theatre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='show_theatre', to='dashboard.theatre'),
        ),
    ]
