# Generated by Django 2.2 on 2019-04-19 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20190419_0730'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='show',
            options={'ordering': ['date', 'time']},
        ),
        migrations.AlterOrderWithRespectTo(
            name='show',
            order_with_respect_to=None,
        ),
    ]
