# Generated by Django 2.2 on 2019-04-19 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_auto_20190419_0828'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='show',
            options={},
        ),
    ]
