# Generated by Django 2.2 on 2019-04-19 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_auto_20190419_0955'),
    ]

    operations = [
        migrations.AlterOrderWithRespectTo(
            name='show',
            order_with_respect_to=None,
        ),
    ]
