# Generated by Django 2.2 on 2019-04-19 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_auto_20190419_1004'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='show',
            options={'ordering': ['date', 'time']},
        ),
    ]
