# Generated by Django 2.2 on 2019-04-19 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_auto_20190419_1121'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='show',
            options={},
        ),
    ]
