# Generated by Django 2.2 on 2019-05-13 18:27

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_auto_20190419_1122'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0005_booking_user'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='booking',
            unique_together={('show', 'row_num', 'col_num', 'user')},
        ),
    ]
