# Generated by Django 2.2 on 2019-05-13 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_auto_20190419_1122'),
        ('main', '0006_auto_20190513_2357'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='booking',
            unique_together={('show', 'row_num', 'col_num')},
        ),
    ]
